### PR TITLE
Fixed batch-mode parameter.

### PR DESCRIPTION
**Pull request by natami**
Updated README.md

### CODE REVIEW

**Review by headcr4sh — APPROVED** [review]
Capital "b" ... yeah... missed that one, too.

**Comment by natami** [comment]
Sorry for the inconvenience :/

- Could you do a new release?

**Comment by RolandNordborg** [comment]
+1 for new release. I could use this too.

**Comment by headcr4sh** [comment]
I am currently on vacation. Will see what I can do.
Might take a few more days than usual...

**Pull request merged**
